// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djvctnpnwweyomfgrfyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqdmN0bnBud3dleW9tZmdyZnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDIzODAsImV4cCI6MjA2NDk3ODM4MH0.7ZgE2W7FZVKUtG5_97qz08hXhdyMK330c6b7tWE_SBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);